version: '3.8'

services:
  postgres:
    image: postgres
    container_name: testpostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5434:5432"
    networks:
      - myNetwork